version: "3"

services:
  # The web
  web:
    container_name: web
    build:
      context: "./etc"
      dockerfile: web.dockerfile
    working_dir: /var/www/html
    volumes:
      - ../projects/index.html:/var/www/html/index.html
      - ../projects/gossby:/var/www/html/gossby
      - ../projects/teawork/api:/var/www/html/teawork/api
      - ../projects/teawork/wordpress:/var/www/html/teawork/wordpress
    ports:
      - 80:80
    # restart: always
    networks:
      docker_network:
        ipv4_address: "10.3.0.16"
  db:
    container_name: db
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_USER: dongtt
      MYSQL_PASSWORD: dongtt
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d
      - docker_db:/var/lib/mysql
    networks:
      docker_network:
        ipv4_address: "10.3.0.14"
networks:
  docker_network:
    driver: "bridge"
    ipam:
      config:
        - subnet: 10.3.0.0/16
volumes:
  docker_db:
